' диаграмма последовательности

@startuml

' Нарисуйте диаграмму последовательности действий (Sequence diagram).
' Отобразите там, как проходит операция чтения списка заказов
' и запись об изменении статуса заказа.
' Там же опишите процесс кеширования с указанием всех сущностей, которые участвуют в кешировании.

' участники

' клиент
participant "MES"
participant "MES API"
participant "Кэш"
database "MES DB"
queue "Message Queue"

' чтение списка заказов
== чтение списка заказов ==

"MES" -> "MES API" : запросить заказы
"MES API" -> "Кэш" : читать заказы
"Кэш" -> "Кэш" : искать заказы
alt Заказы найдены в кэше
    "Кэш" --> "MES API": заказы
else Заказы не найдены (cache miss)
    "Кэш" -> "MES DB": запросить заказы из БД
    "MES DB" --> "Кэш": вернуть данные заказов
    "Кэш" -> "Кэш": кэшировать полученные заказы
    "Кэш" --> "MES API": заказы
end
"MES API" --> "MES" : заказы

' запись изменения статуса
== запись изменения статуса ==

"MES" -> "MES API" : запрос изменения статуса заказа
"MES API" -> "Кэш" : изменить статус заказа
"Кэш" -> "MES DB" : обновить статус заказа
note right: согласно паттерну Write-through
alt Успешная запись
    "MES DB" --> "Кэш": подтверждение записи
    "Кэш" -> "Кэш" : обновить статус заказа
    "Кэш" --> "MES API": подтверждение записи
else Ошибка записи
    "MES DB" --> "Кэш": ошибка записи
    "Кэш" --> "MES API": ошибка записи
end
"MES API" --> "MES" : подтверждение/ошибка изменения статуса заказа

' обработка изменения статуса, пришедшего из очереди
== обработка изменения статуса, пришедшего из очереди ==

"Message Queue" ->> "MES API" : запрос изменения статуса заказа
"MES API" -> "Кэш" : изменить статус заказа
"Кэш" -> "MES DB" : обновить статус заказа
note right: согласно паттерну Write-through
alt Успешная запись
    "MES DB" --> "Кэш": подтверждение записи
    "Кэш" -> "Кэш" : обновить статус заказа
    "Кэш" --> "MES API": подтверждение записи
else Ошибка записи
    "MES DB" --> "Кэш": ошибка записи
    "Кэш" --> "MES API": ошибка записи
    "MES API" ->> "Message Queue": ошибка изменения статуса заказа
end

@enduml